### ISSUE TITLE
Migrate settings from the old go

### ISSUE THREAD

**Issue by mark-crichton** [lchsiteam/lchs-go-new#75]
To ease migration to the new go, we should detect if the user has settings from the old go and translate them into the new go's settings

**Comment by Apricitine** [comment]
gud, but how to do
localStorage isn't shared right? so we'd have to put the old go localStorage settings in a cookie and write an api route to give the cookie data to the new go

or maybe (in the old go) give the user an option to export their settings into a link for the new go (i think that's already a feature in the new go so this would be easier to implement)

**Comment by aschmitigal22** [comment]
New go already has loading settings from a url generated by the "Share Settings" button on the settings page. If you add a button to the old go settings page that constructs a valid link from the settings then you could just link them to new go and it will load them all.

The share button on new go just JSON.stringify()'s the settings and creates the url with the parameters `?setSettings=<string here>&settings` (&settings so that you show up on the settings page when the page loads). The code for this on [Line 416 in vueScript.js](https://github.com/lchsiteam/lchs-go-new/blob/246f806bb519e0f77b5df45d042d3ee8c0ed4e69/vueScript.js#L416)

**Comment by awesomehaze** [comment]
Good to close?

**Comment by Apricitine** [comment]
yup
